
all:
	@echo "CURDIR=$(CURDIR)"
	@echo "MAKEFILES=$(MAKEFILES)"
	@echo "MAKEFLAGS=$(MAKEFLAGS)"
	@echo "LOCAL_VAR=$(LOCAL_VAR)"
	@echo "CHIP=$(CHIP)"
	@echo "t2 build done"

clean:
	@echo "t2 clean done"
